# Generated by Django 3.0.4 on 2020-03-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofiledb',
            name='profile_pic',
            field=models.CharField(max_length=500),
        ),
    ]
