# Generated by Django 3.0.4 on 2020-03-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20200328_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofiledb',
            name='profile_pic',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='gymexpertprofiledb',
            name='profile_pic',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofiledb',
            name='profile_pic',
            field=models.CharField(max_length=500),
        ),
    ]
