# Generated by Django 3.0.4 on 2020-04-02 09:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20200328_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMembershipDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('plan', models.CharField(max_length=100)),
                ('vallet', models.CharField(max_length=100)),
                ('expery_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.UserProfileDB')),
            ],
        ),
    ]
