# Generated by Django 3.0.4 on 2020-04-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_auto_20200404_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledb',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofiledb',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofiledb',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofiledb',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
