# Generated by Django 3.0.4 on 2020-04-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_auto_20200404_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermembershipdb',
            name='expery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermembershipdb',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
